### ISSUE TITLE
Red flag: shallow classes

### ISSUE THREAD

**Issue by palrogg** [IMICovidou/Covidou#23]
Current project uses one class per object. It may overcomplicate further developments. For example, to find why the phone animation differs from device to device, you need to navigate through:
- protoScene.js
- wakeUpCard.js
- phone.js

to find PHONE STATE actually gets updated at every frame without using delta time from Phaser internal clock.

One-time-use objects should be managed in cards to improve readability and reduce verbosity.

Also, they should'nt contain unexpected triggers / game mechanics, which belong to scene and cards. For example `this.parent_scene.dialogue.display(WAKE_UP_ID)` shouldn't be part of the Phone class.

Suggestions:
* deep classes (cf. [Modular Design / Classes Should be Deep](https://web.stanford.edu/~ouster/cgi-bin/cs190-winter18/lecture.php?topic=modularDesign))
* we must use Phaser's built-in features or we'll run out of time. Examples: [Tween Task](https://rexrainbow.github.io/phaser3-rex-notes/docs/site/tween/), [Update Loop](https://photonstorm.github.io/phaser3-docs/Phaser.Time.Clock.html#update)

**Comment by Dobios** [comment]
Yes I'm aware of the issues you're stating. The reason behind them was mostly trying to get the prototype up and running as quickly as possible.  

> this.parent_scene.dialogue.display(WAKE_UP_ID) shouldn't be part of the Phone class.  

I would say that this is quite debatable since the logic behind it is to make each object separate and make their separation as useful as possible. By this I mean that, for example in this specific case, the object isn't implementing any new mechanic, since said mechanic is implemented in the dialogue controller. The phone only takes care of handling any interaction that happens with it. So in that sense, if one wants to find out why the a certain animation is buggy, it would make sense to directly look at the object that is being animated. I would rather do that than clutter the scene class and handle everything in there, which I think will worsen the readability of the code.

I do however agree that _simple_ single use objects should be moved to their respective cards or should use a more generic version of themselves.
